### ISSUE TITLE
SGV and Incunabula ARK URLs not working

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/ark-resolver#11]

**Comment by benjamingeer** [comment]
If I remember correctly, the Incunabula ARK URLs generated by the old SALSAH can’t work with Knora, because the old SALSAH uses project shortcode 0801 for Incunabula, but in Knora, 0801 is BEOL. Is that the problem here?

**Comment by subotic** [comment]
I don't think so. The ARK resolver says that these URLs are invalid:

Incunabula Narrenschiff (lat.): https://ark.dasch.swiss/ark:/72163/0803-3b7598ebb7b-9.201986
SGV Image SGV_04P_03518.TIF: http://ark.dasch.swiss/ark:/72163/0812-1388a5fb712a4-d.201986

**Comment by benjamingeer** [comment]
I can’t check now, but I think the timestamp is invalid. The PHP code has a bug causing it to omit leading zeros before the month and day. Try it with this timestamp: 20190806

**Comment by subotic** [comment]
incunabula: https://ark.dasch.swiss/ark:/72163/0803-3b7598ebb7b-9.20190806
SGV: http://ark.dasch.swiss/ark:/72163/0812-1388a5fb712a4-d.20190806

**Comment by subotic** [comment]
The project shortcode for SGV is actually `080C` in hexadecimal but the ARK URL provides it as a decimal value of `8012`, which is correct.

**Comment by subotic** [comment]
Great, the `AllowVersion0: true` config setting solved it. Now the two links work.

**Comment by subotic** [comment]
>> but the ARK URL provides it as a decimal value of 0812, which is correct.
> I didn't know that the PHP ARK URLs used decimal instead of hexadecimal for project shortcodes. Is this really necessary? I think it's going to cause confusion. It would be better if the PHP code used hexadecimal, too.

I don't think that Lukas is going to touch the old Salsah code. Anyway, the ARK URLs are out there as they are. Probably easier to assume that `version 0` ARK URLs have the project shortcode as a decimal value and then to transform it, if necessary.

**Comment by benjamingeer** [comment]
> Probably easier to assume that version 0 ARK URLs have the project shortcode as a decimal value and then to transform it, if necessary.

OK, I'll do that.

**Comment by subotic** [comment]
great, thanks :-)

A gift that doesn't stop giving ;-)

**Comment by benjamingeer** [comment]
> The project shortcode for SGV is actually `080C` in hexadecimal but the ARK URL provides it as a decimal value of `0812`, which is correct.

Decimal `0812` converted to hexadecimal is `032C`, not `080C`.

Hexadecimal `080C` converted to decimal is `2060`, not `0812`.

I don't understand what the PHP code is doing. @lrosenth, can you please explain?

**Comment by benjamingeer** [comment]
If it's converting one byte at a time, then would hex `FFFF` be converted to decimal as `255255`?

**Comment by benjamingeer** [comment]
Answer: the PHP SALSAH ARK URLs only contain project codes starting with 08.

**Comment by benjamingeer** [comment]
Here is a SALSAH ARK URL in which the project ID is entirely in hexadecimal:

https://data.dasch.swiss/resources/2126045

It looks like this is inconsistent in the database: some are in decimal, and others are in hexadecimal.

**Comment by benjamingeer** [comment]
It turns out that they're all in hexadecimal, and it's the DaSCH ARK resolver data that needs to be corrected.

**Comment by subotic** [comment]
The original issue was fixed by changing the config. For further questions and bugs, please open separate issues.
