### ISSUE TITLE
Github Webhook Security Token

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/ark-resolver#8]
I should have thought, that it is a bit more complicated: https://developer.github.com/webhooks/securing/

Sorry for the extra work.

**Comment by benjamingeer** [comment]
No problem! Will do this on Monday.

**Comment by benjamingeer** [comment]
I think I've implemented what it says to do, but I don't know how to test it. Can you check whether it works?

**Comment by subotic** [comment]
cool, thanks. I will try it out.

**Comment by subotic** [comment]
cool, it seems to be working. The resolver now answeres with as `204`. Thanks :-)

**Comment by benjamingeer** [comment]
Glad to hear it!

**Comment by subotic** [comment]
You can find the webhook settings here: https://github.com/dhlab-basel/dasch-ark-resolver-data/settings/hooks/80842207
