### ISSUE TITLE
Exception: Method HEAD not allowed for URL /config

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/ark-resolver#9]
```
[2019-07-09 09:28:41 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://ark.dasch.swiss/config'
ark_1  | Traceback (most recent call last):
ark_1  |   File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 736, in handle_request
ark_1  |     handler, args, kwargs, uri = self.router.get(request)
ark_1  |   File "/usr/local/lib/python3.7/site-packages/sanic/router.py", line 396, in get
ark_1  |     return self._get(request.path, request.method, "")
ark_1  |   File "/usr/local/lib/python3.7/site-packages/sanic/router.py", line 435, in _get
ark_1  |     raise method_not_supported
ark_1  | sanic.exceptions.MethodNotSupported: Method HEAD not allowed for URL /config
ark_1  | [2019-07-09 09:28:41 +0000] - (sanic.access)[INFO][172.18.0.5:38214]: HEAD http://ark.dasch.swiss/config  405 46
```

**Comment by subotic** [comment]
Maybe you could take a look when you have some time. Thanks.

**Comment by benjamingeer** [comment]
Do we need to support method `HEAD` for URL `/config`? Is `GET` not sufficient?

**Comment by subotic** [comment]
I have no idea. I just see that something is accessing via HEAD and that an exception is thrown :-)

I think that Uptimerobot is using this to test if the service is alive. Looking at the description of `HEAD`, it sound useful:

===>>> https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
9.4 HEAD

The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification.

The response to a HEAD request MAY be cacheable in the sense that the information contained in the response MAY be used to update a previously cached entity from that resource. If the new field values indicate that the cached entity differs from the current entity (as would be indicated by a change in Content-Length, Content-MD5, ETag or Last-Modified), then the cache MUST treat the cache entry as stale.
